### PR TITLE
fix two URL-related bugs: #20 (WSL) & #22 (Windows)

### LINKED ISSUE #20: WSL bug: url hash params cut-off
In WSL,
```julia
DefaultApplication.open("https://google.com/#Blah")
```
opens just `https://google.com` in the browser.
(On Windows, it does the correct thing)

Strangely, if you do 
```julia
run(`powershell.exe -NoProfile -NonInteractive -Command start '"https://google.com/#Blah"'`, wait=false)
```
(which seems to be what DefaultApplication does in WSL),
then it does work correctly!

i.e. here, the first command opens `https://google.com` in my (Windows) browser, while the second opens `https://google.com/#Blah`:
image

---
For context, my use case:
- https://github.com/tfiers/PkgGraph.jl/issues/96

### PR DESCRIPTION
**Pull request by tfiers**
Re
- https://github.com/tpapp/DefaultApplication.jl/issues/20

This PR checks whether the `filename` is an existing file or directory, and only then `relpath`s it

(the `try catch` for the `relpath` is added cause `relpath` on WSL fails if the given path has too many characters)

EDIT:
This PR now also fixes the (slightly related)
- #22 

It does that by calling @cjdoris's powershell command for WSL also on Windows, iff the command crosses the `cmd.exe` limit of 8191 characters

### CODE REVIEW

**Comment by tfiers** [comment]
Re @cjdoris: I edited your code with a check. Ok for you too?

**Comment by tfiers** [comment]
Updated this branch to also fix
- #22

**Comment by tfiers** [comment]
Tested manually, on both WSL and Windows, using:
```
julia> using DefaultApplication

julia> link = "https://google.com/#" * ("x"^8200);

julia> DefaultApplication.open(link);

julia>  DefaultApplication.open("README.md");
```
..which all works now

File: src/DefaultApplication.jl [hunk 1]
```diff
@@ -22,21 +22,47 @@ function open(filename; wait = false)
...
+        end
+        run(_powershell_start_cmd(path); wait = wait)
     elseif Sys.islinux() || Sys.isbsd()
         run(`xdg-open $(filename)`; wait = wait)
     elseif Sys.iswindows()
-        cmd = get(ENV, "COMSPEC", "cmd.exe")
-        run(`$(cmd) /c start $(filename)`; wait = wait)
+        cmd_exe = get(ENV, "COMSPEC", "cmd.exe")
+        cmd = `$(cmd_exe) /c start $(filename)`
+        if _win__cmd_is_too_long(cmd)
```
Comment (tpapp) [inline src/DefaultApplication.jl:38]: Since this is used in one place, it does not warrant a separate function. Just evaluate the length directly here and add the comment from below.

File: src/DefaultApplication.jl [hunk 2]
```diff
@@ -22,21 +22,47 @@ function open(filename; wait = false)
...
     else
         @warn("Opening files the default application is not supported on this OS.",
               KERNEL = Sys.KERNEL)
     end
 end
 
+# https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation
+_win__cmd_is_too_long(cmd) = length(string(cmd)) > 8191
+
+_powershell_start_cmd(path) = `powershell.exe -NoProfile -NonInteractive -Command start \"$(path)\"`
```
Comment (tpapp) [inline src/DefaultApplication.jl:51]: Please use `function ... end`, add a docstring, and put the comment in the body.

File: test/windows.jl [hunk 3]
```diff
@@ -0,0 +1,13 @@
+
+# Tests for WSL and Windows issues #20 and #22
+# (https://github.com/tpapp/DefaultApplication.jl/pull/21)
+#
+# Not run automatically, yet
```
Comment (tpapp) [inline test/windows.jl:5]: please make them run automatically

**Review by tpapp — CHANGES_REQUESTED** [review]
Thanks for the nice work, I asked for some minor changes.

Setting up CI for Windows is not a precondition for merging this PR, but it would be nice.

**Comment by tfiers** [comment]
Thank you for the review.

For the testing, what do you think about factoring `open` into two functions, with one returning the `Cmd` objects, and the other actually `run`ning them.
That way, testing is easier

**Comment by tpapp** [comment]
Great idea, please do it.

**Comment by tfiers** [comment]
Voila, all the above done.
Let's test if the new CI works

**Comment by tfiers** [comment]
Ok I ran the actions on my own branch. After the last two commits they run succesfully now, down to 1.0: https://github.com/tfiers/DefaultApplication.jl/actions/runs/4131800096

(Cloning the registry, in the buildpkg step, makes the windows and macos runs slow; this could be cached I suppose)

**Review by tpapp — APPROVED** [review]
LGTM, thanks!
